file_auto_update:
  # Warning before using
  # This may or may not bring back comments that are deleted
  #
  # This is only intended to be used
  # if you want your config to update to the new config automatically without you doing it
  #
  # This can also mess up some formatting as well.
  enabled: false
  files:
    - 'config'
    - 'messages'

settings:
  use_custom_health: false

player:
  default_class: 'Unspecialized'

formulas:
  player:
    base_health: '100.0'
    maximum_experience: '({player_level} * 250)^1.25'
  entity:
    base_health: '20.0'

weapon:
  lore:
    - ' '
    - '&7Info'
    - '&7» Type: &f{item_type}'
    - '&7» Rarity: &f{item_rarity}'
    - ' '
    - '&7Requirements'
    - '&7» Required Level: &f{item_required_level}'
    - '&7» Required Strength: &f{item_required_str}'
    - '&7» Required Intelligence: &f{item_required_int}'
    - '&7» Required Constitution: &f{item_required_con}'
    - '&7» Required Dexterity: &f{item_required_dex}'
    - '&7» Required Charisma: &f{item_required_cha}'
    - '&7» Required Wisdom: &f{item_required_wis}'
    - '&7» Required Luck: &f{item_required_luk}'
    - ' '
    - '&7Weapon Stats'
    - '&7» Melee Damage: &f{item_melee_minimum_damage}&7-&f{item_melee_maximum_damage}'
    - '&7» Ranged Damage: &f{item_ranged_minimum_damage}&7-&f{item_ranged_maximum_damage}'
    - '&7» Cooldown: &f{item_attack_cooldown}'
    - '&7» Strength: &f{item_str}'
    - '&7» Intelligence: &f{item_int}'
    - '&7» Constitution: &f{item_con}'
    - '&7» Dexterity: &f{item_dex}'
    - '&7» Charisma: &f{item_cha}'
    - '&7» Wisdom: &f{item_wis}'
    - '&7» Luck: &f{item_luk}'
    - ' '
    - '&7Scroll Sockets'
    - '&7» &f{item_scroll_sockets}'
    - ' '
    - '&7Gem Sockets'
    - '&7» &f{item_gem_sockets}'
    - ' '
    - '&7Weapon Description'
    - '&f{item_description}'
    - ' '

armor:
  lore:
    - ' '
    - '&7Info'
    - '&7» Type: &f{item_type}'
    - '&7» Rarity: &f{item_rarity}'
    - ' '
    - '&7Requirements'
    - '&7» Required Level: &f{item_required_level}'
    - '&7» Required Strength: &f{item_required_str}'
    - '&7» Required Intelligence: &f{item_required_int}'
    - '&7» Required Constitution: &f{item_required_con}'
    - '&7» Required Dexterity: &f{item_required_dex}'
    - '&7» Required Charisma: &f{item_required_cha}'
    - '&7» Required Wisdom: &f{item_required_wis}'
    - '&7» Required Luck: &f{item_required_luk}'
    - ' '
    - '&7Armor Stats'
    - '&7» Protection: &f{item_protection}'
    - '&7» Health: &f{item_health}'
    - '&7» Regeneration: &f{item_regeneration}'
    - '&7» Strength: &f{item_str}'
    - '&7» Intelligence: &f{item_int}'
    - '&7» Constitution: &f{item_con}'
    - '&7» Dexterity: &f{item_dex}'
    - '&7» Charisma: &f{item_cha}'
    - '&7» Wisdom: &f{item_wis}'
    - '&7» Luck: &f{item_luk}'
    - ' '
    - '&7Scroll Sockets'
    - '&7» &f{item_scroll_sockets}'
    - ' '
    - '&7Gem Sockets'
    - '&7» &f{item_gem_sockets}'
    - ' '
    - '&7Armor Description'
    - '&f{item_description}'
    - ' '
